import { Product } from "../ModernProductLayout";

export const metalBoxData: Product[] = [
  {
    id: "1",
    code: "S01",
    title: "Silver Series (0.70mm Thick)",
    description: " Electric modular metal box silver series.",
    image: "/products/metalBox/IMG_7304.jpg",
    specifications: {
      S01: "1 or 2 Model - packing 150",
      S03: "3 Model - packing 110",
      S04: "4 Model - packing 100",
      S06: "6 Model - packing 70",
      S08H: "8 Model HZ - packing 50",
      S08SQ: "8 Model SQ - packing 40",
      S12: "12 Model - packing 60",
      S16: "16 Model - packing 25",
      S18: "18 Model - packing 30",
    },
    category: "Electric Modular Metal Box",
  },
  {
    id: "2",
    code: "P01",
    title: "Platinum Series (1.00mm Thick)",
    description: " Electric modular metal box Platinum series.",
    image: "/products/metalBox/IMG_7279.jpg",
    specifications: {
      P01: "1 or 2 Model - packing 150",
      P03: "3 Model - packing 120",
      P04: "4 Model - packing 120",
      P06: "6 Model - packing 80",
      P08H: "8 Model HZ - packing 80",
      P08SQ: "8 Model SQ - packing 80",
      P12: "12 Model - packing 60",
      P16: "16 Model - packing 40",
      P18: "18 Model - packing 30",
    },
    category: "Electric Modular Metal Box",
  },
  {
    id: "3",
    code: "G01",
    title: "Gold Series (0.80mm Thick)",
    description: "Electric modular metal box Gold series.",
    image: "/products/metalBox/IMG_7277.jpg",
    specifications: {
      G01: "1 or 2 model - packing 150",
      G03: "3 model - packing 120",
      G04: "4 model - packing 120",
      G06: "6 model - packing 80",
      G08H: "8 model HZ - packing 80",
      G08SQ: "8 model SQ - packing 80",
      G12: "12 model - packing 60",
      G16: "16 model - packing 40",
      G18: "18 model - packing 30",
    },
    category: "Electric Modular Metal Box",
  },
  {
    id: "4",
    code: "D01",
    title: "Diamond Series (1.2mm Thick)",
    description: "Electric modular metal box Diamond series.",
    image: "/products/metalBox/IMG_7300.jpg",
    specifications: {
      D01: "1 or 2 model - packing 150",
      D03: "3 model - packing 120",
      D04: "4 model - packing 120",
      D06: "6 model - packing 80",
      D08H: "8 model HZ - packing 80",
      D08SQ: "8 model SQ - packing 80",
      D12: "12 model - packing 60",
      D16: "16 model - packing 40",
      D18: "18 model - packing 30",
    },
    category: "Electric Modular Metal Box",
  },
];
